# Configuración global
global:
  checkNewVersion: false
  sendAnonymousUsage: false

# Configuración de logs
log:
  level: DEBUG
  format: common

# Puntos de entrada
entryPoints:
  web:
    address: ":80"
  traefik:
    address: ":8080"

# Proveedores
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: "app-network"
    watch: true
    
  file:
    filename: "/etc/traefik/dynamic_conf.yml"
    watch: true

# Configuración de la API y Dashboard
api:
  dashboard: true
  insecure: true
  debug: true
